parameters:
  - name: environment
    type: string
    default: "dev"

jobs:
  - deployment: terraform_apply
    displayName: "Terragrunt apply (pipeline-only)"
    environment: ${{ parameters.environment }}
    pool:
      vmImage: "ubuntu-latest"
    strategy:
      runOnce:
        deploy:
          steps:
            - download: current
              artifact: tfplan
            - download: current
              artifact: tfplan-json
            - script: |
                set -euo pipefail
                echo "Installing terragrunt for apply"
                sudo apt-get update -y
                sudo apt-get install -y curl coreutils
                TG_VERSION="0.55.12"
                curl -fsSL "https://github.com/gruntwork-io/terragrunt/releases/download/v${TG_VERSION}/terragrunt_linux_amd64" -o /tmp/terragrunt_linux_amd64
                curl -fsSL "https://github.com/gruntwork-io/terragrunt/releases/download/v${TG_VERSION}/terragrunt_linux_amd64.sha256" -o /tmp/terragrunt_linux_amd64.sha256
                echo "$(cat /tmp/terragrunt_linux_amd64.sha256)  /tmp/terragrunt_linux_amd64" > /tmp/terragrunt_sha_check
                sha256sum -c /tmp/terragrunt_sha_check
                sudo mv /tmp/terragrunt_linux_amd64 /usr/local/bin/terragrunt
                sudo chmod +x /usr/local/bin/terragrunt
              displayName: "Install terragrunt"
            - script: |
                set -euo pipefail
                echo "Setting HCS credentials from pipeline variables"
                export TF_VAR_hcs_access_key="$(TF_VAR_hcs_access_key)"
                export TF_VAR_hcs_secret_key="$(TF_VAR_hcs_secret_key)"
                # The plan artifact is downloaded into the pipeline workspace under tfplan/
                if [ -f tfplan/tfplan ]; then
                  echo "Applying terragrunt plan"
                  terragrunt apply -input=false -auto-approve tfplan/tfplan
                else
                  echo "Plan artifact not found; aborting apply"
                  exit 1
                fi
              displayName: "terragrunt apply from plan"
